import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CheckoutsLayout({ children }) {
  return <main>{children}</main> ;
}
